# Generated by Django 2.2.12 on 2020-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pice',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
