# Generated by Django 2.2.12 on 2020-06-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_profile_pice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pice',
            new_name='profile_pic',
        ),
    ]
